### PR TITLE
Upgrade runtime to 6.7

### PR DESCRIPTION
**Pull request by j8r**

### CODE REVIEW

**Comment by j8r** [comment]
@OpenSauce04 is it good for you? I see you are not watching the repository, you might not be aware of this PR.

**Comment by OpenSauce04** [comment]
@j8r Sorry this completely slipped by me. I thought I was watching the repo, but I was mistaken 
It is quite late at the moment, so I will look at this tomorrow

**Comment by j8r** [comment]
Any news? The build is successful.

**Comment by OpenSauce04** [comment]
Sorry, I've been having a tough time juggling Lime3DS development and finals 😅
I will get to this soon, I promise

**Comment by OpenSauce04** [comment]
bot, build io.github.lime3ds.Lime3DS

**Comment by OpenSauce04** [comment]
Works fine on my end, thanks!

**Pull request merged**
